groupName: acme.308.no

# Externally reachable hostname or IP to reach our dns server on port 53
externalServerAddress: ""

# Email address of hostmaster to be used in SOA record reply
hostmasterEmailAddress: ""

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/femfirefem/cert-manager-dns-standalone-webhook-image
  tag: v0.1.10
  pullPolicy: IfNotPresent
  #pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  webhookPort: 443
  dnsPort: 53

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
