apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-manager-dns-standalone-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-dns-standalone-webhook.name" . }}
    chart: {{ include "cert-manager-dns-standalone-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cert-manager-dns-standalone-webhook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cert-manager-dns-standalone-webhook.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cert-manager-dns-standalone-webhook.fullname" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        sysctls:
          - name: "net.ipv4.ip_unprivileged_port_start"
            value: "0"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
            - name: EXTERNAL_SERVER_ADDRESS
              value: {{ .Values.externalServerAddress | quote }}
            - name: ACME_NS_ROOT_ADDRESS
              value: {{ .Values.acmeNsRootAddress | quote }}
            - name: HOSTMASTER_EMAIL_ADDRESS
              value: {{ .Values.hostmasterEmailAddress | quote }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: dns
              containerPort: 53
              protocol: UDP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - "ALL"
              add:
                - "NET_BIND_SERVICE"
      volumes:
        - name: certs
          secret:
            secretName: {{ include "cert-manager-dns-standalone-webhook.servingCertificate" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
