apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-dns-standalone-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-dns-standalone-webhook.name" . }}
    chart: {{ include "cert-manager-dns-standalone-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webhookPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    app: {{ include "cert-manager-dns-standalone-webhook.name" . }}
    release: {{ .Release.Name }}
